---
title: "MTX_EC_data"
author: "Jacob T Nearing"
date: "2026-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())

source(here::here("Utility_Scripts/helper_functions.R"))
source(here::here("Utility_Scripts/load_data_functions.R"))

library(maaslin3)
library(dplyr)


col_diets = c("High Carb" = "#FF6700", "High Fat"="#56B4E9", "High Protein"="#009E73")
```


```{r}
bug <- load_taxa_data()
bug_common <- bug[,is_common(t(bug))]
  
metadata <- load_meta_data(m4_data = bug)
metadata$Diet <- metadata$`Diet Name`
metadata$Age <- metadata$`age (yr)`
metadata$DogID <- metadata$`Animal Name`
metadata$dietOrder <- metadata$`Diet Order Names`
rownames(metadata) <- metadata$`Metagenomics Sample Number`
```

# MTX ECs
## load maAsLin3 results.
```{r}
##load EC results
##this is run in Figure2_rev
mtx_ec_res <- read.table(here::here("diet_ec_mtx_plog_filt/all_results.tsv"), sep="\t", header=T)
##load model
mtx_ec_res_out <- readRDS(here::here("diet_ec_mtx_plog_filt/model_res.RDS"))


mtx_ec_plot_bal <- maaslin3::maaslin_plot_results("Revisions/Display_Items/From_ex_mtx_rev/",
                                              transformed_data = mtx_ec_res_out$transformed_data,
                                              unstandardized_metadata = mtx_ec_res_out$metadata,
                                              fit_data_abundance = mtx_ec_res_out$fit_data_abundance,
                                              fit_data_prevalence = mtx_ec_res_out$fit_data_prevalence,
                                              normalization = "TSS",
                                              transform = "LOG",
                                              coef_plot_vars = c("diet High Protein", "diet High Fat"),
                                              balanced=T, summary_plot_first_n = 15, plot_associations = F)


pathways_of_interest <- unique(mtx_ec_plot_bal$summary_plot$coefficient$data$feature)

mtx_ec_plot_bal$summary_plot$coefficient + theme_bw(base_size = 12)

ggsave(filename="Revisions/Display_Items/From_ex_mtx_rev/summary_plot_final.pdf", height=6, width=8.6)
```

###contributions...

```{r}
#takes in a data frame and splits them into multiple data frames based on a prefix.
split_data_frame_by_prefix <- function(data, prefixes, ec=F){
  #make return list
  split_dfs <- list()
  
  #for each prefix we first select the columns from the original data to pull out
  # and put them in the return list
  for (prefix in prefixes) {
    if(ec==T){
      selected_columns <- select(data, starts_with(paste0(prefix,"|",sep="")))
    }else{
      selected_columns <- select(data, starts_with(paste0(prefix)))
    }

    split_dfs[[prefix]] <- selected_columns
  }
  return(split_dfs)
}

average_contribution_data_prep_RPKM <- function(stratified_data, intFeatures, metadata, bug_data,
                                           contribution_threshold=0.1, ec=F){
  
  ##first we filtered the stratified_data so that it only grabs the intFeatures (features that we are interested in)
  #clean clean up the pathway names to match the naming convention of the pathways of interest
  #colnames(stratified_data) <- stringi::stri_replace_all_regex(colnames(stratified_data), "\\p{Punct}", ".")
  #colnames(stratified_data) <- stringi::stri_replace_all_regex(colnames(stratified_data), "\\s", ".")
  
  #create a list of dfs for each feature of interest where each list contains the contribution in RPKM 
  #of each statified taxon
  split_dfs <- split_data_frame_by_prefix(stratified_data, as.character(intFeatures),ec)
  #check if any of the split_dfs are empty
  #if any are empty this would be an error and we will quit
  for(i in split_dfs){
    stopifnot(dim(i)[2] > 0)
  }
  
  #next we sweep out the RPKM into contribution % (TSS scaling) - we don't do this if we keep RPKMs
  #contribution_values <- list() 
  #for(i in 1:length(split_dfs)){
  #  contribution_values[[i]] <- sweep(split_dfs[[i]], MARGIN = 1, STATS = rowSums(split_dfs[[i]], na.rm = T), '/')
  #}
  
  #Add them all back to one single data frame
  contribution_values_df <- do.call(cbind, unname(split_dfs))
  #stop function if rows don't match up between current df and metadata
  stopifnot(identical(rownames(contribution_values_df), rownames(metadata)))
  
  #Add diet to the new data frame so that it can be melted by diet
  contribution_values_df$Diet <- metadata$Diet
  
  ## melt the data frame by diet and then seperate the feature names by EC (or pathway) and Microbe
  ## note that we say EC here but it could also mean pathway...
  contribution_values_df_melt <- contribution_values_df %>% reshape2::melt(id.vars="Diet") %>%
  tidyr::separate(variable, "\\|", into=c("EC", "Microbe"))

  #We then group by the Diet, EC, and Microbe and calculate the mean contribution for each microbe to that EC
  #within each dietary group
  contribution_values_df_melt_average <- contribution_values_df_melt %>% group_by(Diet, EC, Microbe) %>%
    summarise(mean=mean(value, na.rm=T))

  #set anything below threshold contrubtion to "other"
  #we also set high carb to be negative balues and others as positive this is abused for plotting 
  #although maybe we should just plot them as three individual bars as a dodge position?
  #have to think about this...
  contribution_values_df_melt_average <- contribution_values_df_melt_average %>% ungroup %>%
    mutate(plot_value=ifelse(Diet=='High Carb', -mean, mean)) %>% 
    mutate(Microbe_label=ifelse(mean >= contribution_threshold, Microbe, "Other"))

  #fix microbe labels by matching SGBs
  mic_names <- unique(contribution_values_df_melt_average$Microbe_label)
  ##need to clean these up
  SGB_nums <- gsub(".*\\.t__", "", mic_names)
  SGB_nums <- gsub("_group", "", SGB_nums)
  SGB_matches <- SGB_nums[SGB_nums!="Other"]
  SGB_matches <- SGB_matches[SGB_matches!="unclassified"]

  SGB_indexs <- lapply(SGB_matches, function(x){
    matchs <- grep(x, colnames(bug_data), value=T)
    return(matchs)
  })

  names(SGB_indexs) <- gsub(".*_SGB", "SGB", SGB_indexs)
  names(SGB_indexs) <- gsub("\\.group", "", names(SGB_indexs))
  names(SGB_indexs) <- gsub("_group", "", names(SGB_indexs))
  
  
  ## add it to dataframe
  contribution_values_df_melt_average$SGB <- gsub(".*t__", "", contribution_values_df_melt_average$Microbe_label)
  contribution_values_df_melt_average$SGB <- gsub("\\.group", "", contribution_values_df_melt_average$SGB)
  contribution_values_df_melt_average$SGB <- gsub("_group", "", contribution_values_df_melt_average$SGB)

  contribution_values_df_melt_average$Fixed_names <-
    unlist(SGB_indexs)[match(contribution_values_df_melt_average$SGB, names(SGB_indexs))]
  #fix up some names here
  contribution_values_df_melt_average$Fixed_names[which(contribution_values_df_melt_average$Microbe_label=="Other")] <- "Other"
    contribution_values_df_melt_average$Fixed_names[which(contribution_values_df_melt_average$Microbe_label=="unclassified")] <- "unclassified"
  
  stopifnot(!any(is.na(contribution_values_df_melt_average$Fixed_names)))
    
    return(list(contribution_values_df_melt_average, contribution_values_df_melt))
}


```

###load in EC CPM data
```{r}
##load mtx_ec_strat_CPM
mtx_ec_strat <- load_EC_MTX_data(metadata, strat=T, relab=F)

plot_df_RPKMs <- average_contribution_data_prep_RPKM(stratified_data = mtx_ec_strat, 
                                                     intFeatures = pathways_of_interest, 
                                                     metadata = metadata,
                                                     bug_data = bug, contribution_threshold = 300,
                                                     ec=T)

##we are going to plot them all on positive scale here.
plot_df_RPKMs[[1]]$mean <- abs(plot_df_RPKMs[[1]]$mean)
##set factors for Diet so we know what order they are displayed.
plot_df_RPKMs[[1]]$Diet <- factor(plot_df_RPKMs[[1]]$Diet, levels=c("High Carb", "High Protein", "High Fat"))

##get colors
mycolors <- Polychrome::palette36.colors(20)
mycolors <- unname(mycolors)

levels(pathways_of_interest)

#set EC as factor so they are plotted consistently
plot_df_RPKMs[[1]]$EC <- factor(plot_df_RPKMs[[1]]$EC, levels=levels(pathways_of_interest))


### grab everything that is over 2500

grps <- plot_df_RPKMs[[1]] %>% group_by(EC, Diet) %>% summarize(sum(mean))

small_values <- unique(grps$EC[which(grps$`sum(mean)` > 400)])



p1<- plot_df_RPKMs[[1]] %>%
  ggplot(aes(x=mean, y=EC)) + 
  geom_col(aes(fill=Fixed_names), position = "stack", col=NA, linewidth = 0, width=1) + 
  scale_fill_manual(values=mycolors) + theme_classic() +
  facet_grid( ~ Diet, scales="free_y", space="free")

ggsave("Revisions/Display_Items/From_ex_mtx_rev/figures/contribution_CPMs.pdf", width=10, height=8)

p1  + guides(fill="none")
#get the legend for p1
legend <- get_legend(p1)
```


# MGX Pathways

```{r}
average_contribution_data_prep_mgx <- function(stratified_data, intFeatures, metadata, bug_data,
                                           contribution_threshold=0.1){
  
  ##first we filtered the stratified_data so that it only grabs the intFeatures (features that we are interested in)
  #clean clean up the pathway names to match the naming convention of the pathways of interest
  #colnames(stratified_data) <- stringi::stri_replace_all_regex(colnames(stratified_data), "\\p{Punct}", ".")
  #colnames(stratified_data) <- stringi::stri_replace_all_regex(colnames(stratified_data), "\\s", ".")
  #create a list of dfs for each feature of interest where each list contains the contribution in RPKM 
  #of each statified taxon
  split_dfs <- split_data_frame_by_prefix(stratified_data, as.character(intFeatures))

  
  #check if any of the split_dfs are empty
  #if any are empty this would be an error and we will quit
  for(i in split_dfs){
    stopifnot(dim(i)[2] > 0)
  }
  
  #next we sweep out the RPKM into contribution % (TSS scaling)
  ## this can create NAs when everything is 0 for a pathway in that sample.
  contribution_values <- list() 
  for(i in 1:length(split_dfs)){
    contribution_values[[i]] <- sweep(split_dfs[[i]], MARGIN = 1, STATS = rowSums(split_dfs[[i]], na.rm = T), '/')
  }
  
  #Add them all back to one single data frame
  contribution_values_df <- do.call(cbind, contribution_values)
  #stop function if rows don't match up between current df and metadata
  stopifnot(identical(rownames(contribution_values_df), rownames(metadata)))
  
  #Add diet to the new data frame so that it can be melted by diet
  contribution_values_df$Diet <- metadata$Diet
  
  ## melt the data frame by diet and then seperate the feature names by EC (or pathway) and Microbe
  ## some of these can be NA (i.e. they didn't contribute)
  contribution_values_df_melt <- contribution_values_df %>% reshape2::melt(id.vars="Diet") %>%
  tidyr::separate(variable, "\\|", into=c("EC", "Microbe"))

  #We then group by the Diet, EC, and Microbe and calculate the mean contribution for each microbe to that EC
  #within each dietary group
  ## We also remove NAs meaning if a sample didn't have that pathway then they don't show up here. 
  contribution_values_df_melt_average <- contribution_values_df_melt %>% group_by(Diet, EC, Microbe) %>%
    summarise(mean=mean(value, na.rm=T))

  #set anything below 10% contrubtion to "other"
  contribution_values_df_melt_average <- contribution_values_df_melt_average %>% ungroup %>%
    mutate(plot_value=ifelse(Diet=='High Carb', -mean, mean)) %>% 
    mutate(Microbe_label=ifelse(mean >= contribution_threshold, Microbe, "Other"))

  #fix microbe labels by matching SGBs
  mic_names <- unique(contribution_values_df_melt_average$Microbe_label)
  ##need to clean these up
  ##need to clean these up
  SGB_nums <- gsub(".*\\.t__", "", mic_names)
  SGB_nums <- gsub("_group", "", SGB_nums)
  SGB_matches <- SGB_nums[SGB_nums!="Other"]
  SGB_matches <- SGB_matches[SGB_matches!="unclassified"]

  SGB_indexs <- lapply(SGB_matches, function(x){
    matchs <- grep(x, colnames(bug_data), value=T)
    return(matchs)
  })

  names(SGB_indexs) <- gsub(".*_SGB", "SGB", SGB_indexs)
  names(SGB_indexs) <- gsub("\\.group", "", names(SGB_indexs))
  names(SGB_indexs) <- gsub("_group", "", names(SGB_indexs))
  
  
  ## add it to dataframe
  contribution_values_df_melt_average$SGB <- gsub(".*t__", "", contribution_values_df_melt_average$Microbe_label)
  contribution_values_df_melt_average$SGB <- gsub("\\.group", "", contribution_values_df_melt_average$SGB)
  contribution_values_df_melt_average$SGB <- gsub("_group", "", contribution_values_df_melt_average$SGB)

  contribution_values_df_melt_average$Fixed_names <-
    unlist(SGB_indexs)[match(contribution_values_df_melt_average$SGB, names(SGB_indexs))]
  #fix up some names here
  contribution_values_df_melt_average$Fixed_names[which(contribution_values_df_melt_average$Microbe_label=="Other")] <- "Other"
    contribution_values_df_melt_average$Fixed_names[which(contribution_values_df_melt_average$Microbe_label=="unclassified")] <- "unclassified"
  
  stopifnot(!any(is.na(contribution_values_df_melt_average$Fixed_names)))
  
  return(contribution_values_df_melt_average)
}
```

```{r}
pathway_strat <- load_pathway_data(metadata=metadata, strat=T, remove_unknown = F)

pathway_result_rds <- readRDS("Functional_MaAsLin3/Diet_rev_path/all_data.RDS")

pathway_plot_bal <- maaslin_plot_results("Functional_MaAsLin3/Diet_rev_path/",
                                              transformed_data = pathway_result_rds$transformed_data,
                                              unstandardized_metadata = pathway_result_rds$metadata,
                                              fit_data_abundance = pathway_result_rds$fit_data_abundance,
                                              fit_data_prevalence = pathway_result_rds$fit_data_prevalence,
                                              normalization = "TSS",
                                              transform = "LOG",
                                              coef_plot_vars = c("Diet High Protein", "Diet High Fat"),
                                              balanced=T, summary_plot_first_n = 15, plot_associations = F)

pathways_of_interest <- unique(pathway_plot_bal$summary_plot$coefficient$data$feature)

pathway_plot_bal$summary_plot$coefficient + theme_bw(base_size = 12) + scale_x_continuous(limits = c(-2.2, 3.5))

ggsave(filename="Revisions/Display_Items/From_Figure3_script/pathway_coef_plot.pdf", height=6, width=12)

```


## Contribution plot

```{r}



plot_df_mgx <- average_contribution_data_prep_mgx(stratified_data = pathway_strat, 
                                                     intFeatures = pathways_of_interest, 
                                                     metadata = metadata,
                                                     bug_data = bug, contribution_threshold = 0.15)

##we are going to plot them all on positive scale here.
##set factors for Diet so we know what order they are displayed.
plot_df_mgx$Diet <- factor(plot_df_mgx$Diet, levels=c("High Carb", "High Protein", "High Fat"))

##get colors
mycolors <- Polychrome::palette36.colors(n=36)
mycolors <- unname(mycolors)

levels(pathways_of_interest)

#set EC as factor so they are plotted consistently
plot_df_mgx$EC <- factor(plot_df_mgx$EC, levels=levels(pathways_of_interest))


p1<- plot_df_mgx %>%
  ggplot(aes(x=mean, y=EC)) + 
  geom_col(aes(fill=Fixed_names), position = "fill", col=NA, linewidth = 0, width=1) + 
  scale_fill_manual(values=mycolors) + theme_classic() +
  facet_grid( ~ Diet, scales="free_y", space="free") +
  xlab("Mean stratified contribution %")


ggsave("Revisions/Display_Items/From_Figure3_script/contribution_prop.pdf", width=15, height=8)

```

## get total MTX

```{r}
fat_sig <- mtx_ec_res %>% filter(value=="High Fat") %>% filter(is.na(error)) %>% filter(qval_individual < 0.1)
sig_ec_fat <- fat_sig %>% pull(feature)


prot_sig <- mtx_ec_res %>% filter(value=="High Protein") %>% filter(is.na(error)) %>% filter(qval_individual < 0.1)

sig_ec_prot <- prot_sig %>% pull(feature)
sig_ec_prot

length(sig_ec_prot)

length(intersect(sig_ec_prot, sig_ec_fat))
length(setdiff(sig_ec_prot, sig_ec_fat))
length(setdiff(sig_ec_fat, sig_ec_prot))


```


## Lets look at protein catalysis ec expression to help figure5.

```{r}
ec_microbial_protein <- c(
  # Stickland core reductases
  "1.21.4.1",  # D-proline reductase
  "1.21.4.2",  # Glycine reductase
  "1.21.4.3",  # Sarcosine reductase
  "1.21.4.4",  # Betaine reductase

  # Oxidative Stickland / amino acid dehydrogenases
  "1.4.1.1",   # L-alanine dehydrogenase
  "1.4.1.2",   # Glutamate dehydrogenase (NAD+)
  "1.4.1.9",   # Leucine dehydrogenase
  "4.2.1.16",  # L-threonine dehydratase

  # Branched-chain 2-oxoacid dehydrogenase complex
  "1.2.4.4",   # Branched-chain 2-oxoacid dehydrogenase (E1)
  "2.3.1.168", # Dihydrolipoyllysine-residue acyltransferase (E2)
  "1.8.1.4",   # Dihydrolipoyl dehydrogenase (E3)

  # BCAA entry enzymes
  "2.6.1.42",  # Branched-chain amino acid aminotransferase

  # Branched-chain acyl-CoA dehydrogenases & β-oxidation-like steps
  "1.3.8.4",   # Isovaleryl-CoA dehydrogenase
  "1.3.99.10", # Isovaleryl-CoA dehydrogenase (alt. EC)
  "1.3.8.5",   # Branched-chain acyl-CoA dehydrogenase
  "1.3.99.12", # Branched-chain acyl-CoA dehydrogenase (alt. EC)
  "4.2.1.17",  # Enoyl-CoA hydratase
  "1.1.1.35",  # 3-hydroxyacyl-CoA dehydrogenase
  "2.3.1.16",  # 3-ketoacyl-CoA thiolase

  # Valine / isoleucine branch steps
  "6.4.1.4",   # Methylcrotonyl-CoA carboxylase
  "4.2.1.18",  # Methylglutaconyl-CoA hydratase
  "1.2.1.27",  # Methylmalonate-semialdehyde dehydrogenase (acylating)
  "1.1.1.31",  # 3-hydroxyisobutyrate dehydrogenase
  "3.1.2.4",   # 3-hydroxyisobutyryl-CoA hydrolase
  "4.1.3.4",   # 3-hydroxymethylglutaryl-CoA lyase

  # Terminal phosphotransacylase/kinase steps
  "2.3.1.19",  # Phosphotransbutyrylase (rep. phosphotransacylase)
  "2.3.1.8",   # Phosphotransacetylase
  "2.7.2.14"   # Branched-chain-fatty-acid kinase
)


ec_aa_degradation_extra <- c(
  # Broad aminotransferases
  "2.6.1.1", "2.6.1.2", "2.6.1.5", "2.6.1.9", "2.6.1.19", "2.6.1.21",
  # Dehydrogenases / oxidases
  "1.4.1.3", "1.4.1.4", "1.4.1.5", "1.4.1.13", "1.4.1.15", "1.4.1.16",
  "1.4.3.3", "1.4.3.1", "1.4.99.1",
  # Decarboxylases
  "4.1.1.17", "4.1.1.19", "4.1.1.28", "4.1.1.25", "4.1.1.22", "4.1.1.64",
  # Aldehyde dehydrogenases
  "1.2.1.3", "1.2.1.10", "1.2.1.71",
  # Deaminases / lyases
  "4.3.1.17", "4.3.1.19", "4.4.1.1", "4.4.1.8", "4.3.1.3", "4.3.1.15",
  # Arginine/ornithine/urea-cycle related
  "3.5.3.1", "3.5.3.6", "3.5.3.8", "3.5.3.9", "3.5.3.19",
  "2.1.3.3", "3.5.1.15",
  # Aromatic AA degradation
  "1.13.11.11", "1.13.11.52", "1.13.11.27", "1.13.11.5", "1.13.11.39",
  "1.13.11.1", "1.13.11.2",
  # Met/Cys
  "4.4.1.11", "2.1.1.10", "2.5.1.6", "3.13.1.3", "1.13.11.18",
  # Gly/Ser / one-carbon
  "1.4.4.2", "2.1.2.10", "2.1.2.1", "2.1.2.5",
  # Pro / hydroxyproline
  "1.5.5.2", "1.5.1.2", "1.5.1.8", "1.2.1.88",
  # Entry into central metabolism
  "1.2.4.1", "2.3.1.12", "1.2.4.2", "2.3.1.61", "1.1.1.38"
)


fat_all <- mtx_ec_res %>% filter(value=="High Fat") %>% filter(is.na(error))

fat_all_cata <- fat_all %>% filter(feature %in% ec_microbial_protein)
fat_all_cata$feature <- factor(fat_all_cata$feature, levels=c(ec_microbial_protein))

fat_all_cata %>% group_by(qval_individual < 0.1, coef > 0) %>% summarize(n())


fat_all_cata %>% filter(qval_individual < 0.1, coef > 0)


fat_all_cata %>% ggplot(aes(y=feature, x=coef, color=qval_individual)) + geom_point(size=3) +
  theme_bw() + scale_color_continuous()

all_cata <- mtx_ec_res %>% filter(is.na(error)) %>% filter(feature %in% ec_microbial_protein) %>% filter(metadata=="diet")
  

all_cata$feature <- factor(all_cata$feature, levels=ec_microbial_protein)

all_cata %>% ggplot(aes(y=feature, x=coef, fill=qval_individual)) + geom_point(size=3, pch=21) +
  theme_bw() + scale_color_continuous() +
  facet_grid(~ value) +
  xlab("Transcript expression coefficent") +
  ylab("Feature") +
  geom_vline(aes(xintercept = null_hypothesis)) +
  scale

ggsave("Revisions/Display_Items/From_Figure3_script/prot_catalysis.pdf", width=12, height=8)


aa_degrad <- mtx_ec_res %>% filter(is.na(error)) %>% filter(feature %in% ec_aa_degradation_extra) %>% filter(metadata=="diet")

aa_degrad %>% ggplot(aes(y=feature, x=coef, fill=qval_individual)) + geom_point(size=3, pch=21) +
  theme_bw() + scale_color_continuous() +
  facet_grid(~ value) +
  xlab("Transcript overexpression coefficent") +
  ylab("Feature") +
  geom_vline(aes(xintercept = null_hypothesis)) +
  scale

ggsave("Revisions/Display_Items/From_Figure3_script/aa_degration.pdf", width=12, height=8)


test <- aa_degrad %>% filter(value=="High Fat") %>% filter(qval_individual < 0.1)
test2 <- all_cata %>% filter(value=="High Protein") %>% filter(qval_individual < 0.1)


```

#MTX volcano
```{r}

mtx_ec_res %>% filter(metadata=="diet") %>% ggplot(aes(y=-log10(pval_individual), x=coef, color=value, alpha=qval_individual < 0.1)) + geom_point() +
  theme_bw(base_size = 16)

ggsave("Revisions/Display_Items/From_Figure3_script/mtx_volcano.pdf", width=12, height=8)
ggsave("Revisions/Display_Items/From_Figure3_script/mtx_volcano.png", width=12, height=8)

```